FROM xalgorithms/jupyterhub:0.0.1

RUN apt-get update && apt-get -y install python3-pip
RUN pip install git+https://github.com/jupyterhub/oauthenticator.git
RUN apt-get -y --purge remove python3-pip && apt-get -y --purge autoremove

COPY jupyterhub_config.py /srv/jupyterhub


